# Generated by Django 4.0.4 on 2022-08-30 21:17

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_projectroom_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectroom',
            name='enrollment_method',
            field=models.CharField(default='', max_length=200000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectroom',
            name='project_description',
            field=models.CharField(blank=True, max_length=500000, null=True),
        ),
        migrations.AddField(
            model_name='projectroom',
            name='qualifications',
            field=jsonfield.fields.JSONField(default=''),
            preserve_default=False,
        ),
    ]
