# Generated by Django 4.0.4 on 2022-08-31 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_projectroom_enrollment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectroom',
            name='members_needed',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
