# Generated by Django 4.0.4 on 2022-09-07 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_projectroom_members_needed'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectroom',
            name='domain',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
