# Generated by Django 4.0.4 on 2022-09-07 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_projectroom_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectroom',
            name='domain',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
