# Generated by Django 4.0.4 on 2022-09-08 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_projectroom_domain'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectroom',
            old_name='domain',
            new_name='project_location',
        ),
        migrations.AddField(
            model_name='projectroom',
            name='work_experience',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='projectroom',
            name='work_field',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
