# Generated by Django 4.0.4 on 2022-09-18 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_domain_projectroom_project_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JoinProjectRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='', max_length=100)),
                ('email', models.CharField(max_length=200)),
                ('contact_number', models.CharField(max_length=200)),
                ('cv', models.FileField(upload_to='cvs')),
            ],
        ),
    ]
