# Generated by Django 4.0.4 on 2022-09-19 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_joinprojectrequest_intention_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='joinprojectrequest',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='joinprojectrequest',
            name='name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
